### ISSUE TITLE
How to get existing saves to load in game

### ISSUE THREAD

**Issue by mocaaaaaaaa** [m5kro/RPG-Maker-MacOS-Launcher#2]
I'm having an issue where I can't get existing saves to show up. I select the game folder and the app recognizes the save location when I open the save editor (game folder\save\config.rpgsave, global.rpgsave, file1.rpgsave, etc). However if I start the game or export as a standalone app, existing saves and config.rpgsave isn't found by the game. I can make new saves and load them in separate sessions, but I can't figure out how to get my existing saves on there. I tried looking around in devtools to see if I could find the location of the new saves (so I could copy my existing save data over) but I couldn't even find that. Would appreciate any insight on this.

**Comment by m5kro** [comment]
Does your game have a www folder?

**Comment by mocaaaaaaaa** [comment]
Ah I see now. Looks like Shimobashira games use gamefolder\save\file1.rpgsave paths while other RPGM games do gamefolder\www\save\file1.rpgsave. So other games work fine, just not these ones (and manually moving the saves folder doesn't work). I'll poke around in the game js files and see if there's something I can change.

**Comment by mocaaaaaaaa** [comment]
Yup that was it. Those games had their savedir = execpath so the save folder was in the same directory as the game exe. Changed it to savedir = modulepath so that the save folder would show up in www and it worked.
